### ISSUE TITLE
Where to send repository link of certificates.

### ISSUE THREAD

**Issue by Nikhilkumarray** [Bharathgopal/M1_March_2022#115]

**Comment by junaidferoz** [comment]
Create a repository on your account.
there click on create file and new file.
then you will select the certificate and click OK. that should help

**Comment by GuturiDhanushkumar** [comment]
I think they will tell later that were we have to submit that repository link

**Comment by Bharathgopal** [comment]
A submission form will be released on the day of Project submissions.

**Comment by Bharathgopal** [comment]
Duplicate of [Issue 140](https://github.com/Bharathgopal/M1_March_2022/issues/140#issuecomment-1072083117)
