### ISSUE TITLE
Unable to complete Pull Request - First Day on Github

### ISSUE THREAD

**Issue by venu-hub** [Bharathgopal/M1_March_2022#130]
i am just stck at 6 step open a pull request  i e to create a pull request  and its showing error like " at least one approval review is required" so what i have to do sir.

**Comment by Balajiramesh09** [comment]
same problem here, need help

**Comment by junaidferoz** [comment]
could you jest show me a screenshot on what the problem is, so that i can help you more?

**Comment by venu-hub** [comment]
sorry ,but whre is option to add screenshot in this  issue section

**Comment by arnoorlasravan** [comment]
in the comment section below you see an option Attach files by dragging & dropping, selection or pasting them.
using this option you share screenshot

**Comment by venu-hub** [comment]
okk..thanks
![Screenshot (34)](https://user-images.githubusercontent.com/59051114/158723090-e2139206-af40-43aa-beb4-c14b3ecc6627.png)
![Screenshot (35)](https://user-images.githubusercontent.com/59051114/158723095-f076c5cd-9c47-4d31-822b-0c69c5e45122.png)

**Comment by venu-hub** [comment]
i am facing this problem at 6 step
![Screenshot (36)](https://user-images.githubusercontent.com/59051114/158723321-e3f73482-aadf-4f36-8492-51f3e1a30c97.png)

**Comment by venu-hub** [comment]
plese help me ..i am stuck at this i was just trying from 3 -5 days but unable to do that

**Comment by Bharathgopal** [comment]
You may need to add one reviewer account to complete the pullrequest

**Comment by venu-hub** [comment]
but how to add it? sir

**Comment by Amangarg99** [comment]
Hey Venu! 
If you are have created the pull request just click on that pull request . go to **files changed** then you can see 3 dots icon on the right corner ,just click on it . You will get an option to edit file just click on it and make some random changes on line number 5 and commit those changes . your issue will be resolved 

Hope this will help!

**Comment by Bharathgopal** [comment]
https://github.com/Bharathgopal/M1_March_2022/issues/229
