### ISSUE TITLE
Need some help !!!!

### ISSUE THREAD

**Issue by Faadilbatcha** [Bharathgopal/M1_March_2022#131]
![image](https://user-images.githubusercontent.com/101641134/158409830-fd801b6d-ac15-45c6-8338-2959047d3b4a.png)
can u please guide me , what i can do after this @Bharathgopal . Since my page's not working after this step

**Comment by Bharathgopal** [comment]
3 step process is already defined in the web page. Please follow the same

**Comment by Faadilbatcha** [comment]
Thank you, Issue solved
