### ISSUE TITLE
INSTALLATION PROBLEM IN DOXYGEN

### ISSUE THREAD

**Issue by herenajoshika** [Bharathgopal/M1_March_2022#134]
The website to download DOXYGEN is not working 
The error message which is displayed is :

This site can’t be reached
The connection was reset.
Try:

Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_RESET

AND THE WEBSITE WHICH I VISITED TO DOWNLOAD DOXYGEN IS [https://www.doxygen.nl/download.html](https://www.doxygen.nl/download.html)

**Comment by junaidferoz** [comment]
use this link
https://sourceforge.net/projects/doxygen/
