### ISSUE TITLE
 Doubt regarding Git Hub Repository

### ISSUE THREAD

**Issue by Sanskcet** [Bharathgopal/M1_March_2022#138]
Sir 
Is there any name conventions to be followed while creating a Repository(Like as we do have in creating folders in Repo)  as we know a tool is used to evaluate our Certificates.
Thanks in Advance

**Comment by manasiAraspure** [comment]
https://github.com/prithvisekhar/AppliedSDLC_Template
https://github.com/stepin654321/MiniProject_Template

These are the 2 links which are given. May be this helps you understand.

**Comment by Sanskcet** [comment]
> https://github.com/prithvisekhar/AppliedSDLC_Template https://github.com/stepin654321/MiniProject_Template
> 
> These are the 2 links which are given. May be this helps you understand.

Thanks a lot @manasiAraspure
