### ISSUE TITLE
git-hub course problem

### ISSUE THREAD

**Issue by Aishwarya-More-IT** [Bharathgopal/M1_March_2022#145]
In my 2 step(Introduction to git hub) shows your branch is not deployed so, what i do to reached to the last step?

**Comment by Nikhilkumarray** [comment]
do as stating below
click on setting tab
while scrolling keep eye on left side then click on "page" tab 
select "main" branch in source drop down and make sure to save the change.
                                                                                                                                  hope it helps

**Comment by Bharathgopal** [comment]
https://github.com/Bharathgopal/M1_March_2022/issues/229
