### ISSUE TITLE
I am unable to compile the code it is giving error 

### ISSUE THREAD

**Issue by Sreenivas0706** [Bharathgopal/M1_March_2022#148]
usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/9/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
(.text+0x24): undefined reference to `main'
collect2: error: ld returned 1 exit status
The above error i am getting even if i used different method i unable to get the output

**Comment by Bharathgopal** [comment]
[Refer](https://github.com/Bharathgopal/M1_March_2022/issues/144)

Need to make sure main function is part of the program.

**Comment by Bharathgopal** [comment]
Duplicate of 144
