### ISSUE TITLE
writing multiple files

### ISSUE THREAD

**Issue by samanvitha-125** [Bharathgopal/M1_March_2022#163]
when i wrote unity files in seperate folder and include the test files in 3_Implementation , i am getting an error saying unity files not found, can i add the unity files directly into the 3_implementation without keeping in folder?

**Comment by Bharathgopal** [comment]
Specify the proper path of the file and location
* Naming convention - case sensitive
* Add Include path with -I option

* Ignore IDE errors and Focus on Terminal Error on compilation

**Comment by samanvitha-125** [comment]
yes sir got it !
