### ISSUE TITLE
issue in codiga analysis

### ISSUE THREAD

**Issue by samanvitha-125** [Bharathgopal/M1_March_2022#180]
when i performed analysis in codiga, it is showing violations in unity.c files. how to resolve it ?
![Screenshot (66)](https://user-images.githubusercontent.com/62429376/159422960-f8a58f24-7b70-46a8-a528-4bf0c2891583.png)

**Comment by Bharathgopal** [comment]
Find a feature to ignore files that must be excluded form analysis
