### ISSUE TITLE
error in program trial

### ISSUE THREAD

**Issue by Mrityunjai009** [Bharathgopal/M1_March_2022#207]
I have corrected the program but still  terminal is showing old error how to fix it
![Screenshot (127)](https://user-images.githubusercontent.com/101145472/160051685-a7c2d1e7-303a-4cf1-b737-4984d8095a4c.png)

same code run as another name(123.c) and there is the output
![Screenshot (128)](https://user-images.githubusercontent.com/101145472/160052094-5cd31b13-10c8-4121-bdc1-35b2fb78f31e.png)
 is it correct ??

**Comment by Bharathgopal** [comment]
Save files before compiling always. The error is shown clearly on command prompt.
