### ISSUE TITLE
Unable to execute Makefile

### ISSUE THREAD

**Issue by phanikrishna819** [Bharathgopal/M1_March_2022#208]
![Screenshot (247)](https://user-images.githubusercontent.com/57516776/160074846-4aa1c451-49bb-47d5-8414-765bbca821c4.png)

Hi, I tried using makefile and it is showing as no command found, but when I list the files us "ls" command I could identify Makefile in the respective folder. 
Help me in solving this issue

**Comment by Bharathgopal** [comment]
First make needs to be installed. 
Refer to software requirements section on how to install.
