### ISSUE TITLE
Communicating using Markdown-Merge your headers

### ISSUE THREAD

**Issue by Jyoti-Olekar** [Bharathgopal/M1_March_2022#210]
Unable to proceed to the next step 

(https://user-images.githubusercontent.com/101628611/160111090-a827613a-360b-4e76-bcba-04b285e9a164.png)
(https://user-images.githubusercontent.com/101628611/160111081-8fa9fa90-e6aa-4b43-8178-c9510e5d1d33.png)

**Comment by Jyoti-Olekar** [comment]
Next step is to Add an image but I am unable to proceed to it

https://github.com/Jyoti-Olekar/markdown-portfolio/pull/2

**Comment by Bharathgopal** [comment]
https://github.com/Bharathgopal/M1_March_2022/issues/229
