### ISSUE TITLE
valgrinde badge error

### ISSUE THREAD

**Issue by Rishi5254** [Bharathgopal/M1_March_2022#220]
![image](https://user-images.githubusercontent.com/94619066/160292260-0a6369ae-6a7f-417f-988a-a513c3bfb179.png)

Hello Guys, 

Im trying to get valgrind badge but its always failing
Im getiing this error when i try to install valgrind and cunit
Im using this commands to install

* sudo apt-get -y install valgrind
* sudo apt-get -y install libcunit1 libcunit1-doc libcunit1-dev 

## My Code
![Code](https://user-images.githubusercontent.com/94619066/160292745-69e66796-ff98-4c16-92d4-258cebfb4a77.PNG)

## Error Im getting
![error](https://user-images.githubusercontent.com/94619066/160292559-2b85a8d4-1d30-4898-8164-9cae70cd5cb0.PNG)

**Comment by Bharathgopal** [comment]
Expand the apt install valgrind and capture the screenshot. It is not clear what is the error.
