### ISSUE TITLE
Issue in project-file handling

### ISSUE THREAD

**Issue by Pranesh-here** [Bharathgopal/M1_March_2022#224]
For my project I've created two (.c)files, one has function with logic of the project and the other file gets input from user and calls the function.

Unity files are added, but I don't know what are the lines to be added newly which suits my code. And in (.h) file, I don't have an idea about what to be added in the (.h) file. Can anyone provide me a solution for automatic testing using unity files which suits my project.

There's no option available to add label for this issue. Sorry for not adding the label.

**Comment by Bharathgopal** [comment]
https://github.com/Bharathgopal/M1_March_2022/issues/217
