### ISSUE TITLE
error while using wsl, gcc not found

### ISSUE THREAD

**Issue by akkivanguu** [Bharathgopal/M1_March_2022#227]
![Screenshot (17)](https://user-images.githubusercontent.com/101030179/160573890-c4ce6276-f5b2-4685-9138-0a1477afed6f.png)
gcc command not found , why??
even I have already winge gcc  compiler and using in simple vs code for compiling various programs..., but when i install ubuntu and wsl extension... this error is shown..
help!

**Comment by Faadilbatcha** [comment]
U can try out the suggestion, its giving!!!
enter the command
$ sudo apt install gcc 
then this will ask for your Sudo password, once u enter it 
The terminal will Install GCC on by itself, feel free to try!!

**Comment by akkivanguu** [comment]
@Faadilbatcha  I had already try this, what still not work...

**Comment by 4NI18EE046** [comment]
https://linuxize.com/post/how-to-install-gcc-compiler-on-ubuntu-18-04/
follow the three steps provided in the link and you are good to go.
