### ISSUE TITLE
Doubt regarding file structure

### ISSUE THREAD

**Issue by PranithAlva** [Bharathgopal/M1_March_2022#254]
Should all the three c files and header files just placed under 3_implemntation file or should each one of them has to be kept separately in different directories.

**Comment by Amangarg99** [comment]
place all three files under 3_implementation also add your test file here

**Comment by ITSMEUNICK-21** [comment]
Pranith, try to follow this structure if possible :
https://github.com/stepin654321/MiniProject_Template/tree/master/MiniProject_C/3_Implementation

Have a look 
Thank you

**Comment by PranithAlva** [comment]
Thank you guys
