### ISSUE TITLE
I HAVE CHANGED MY SUBMITTY PASSWORD . IS IT OKAY ?

### ISSUE THREAD

**Issue by ROHITVARSHNEY1122** [Bharathgopal/M1_March_2022#258]
BHARATGOPAL , PLEASE GIVE EXPALANATION ON LICENSE FILE OF OUR PROJECT BY CREATIVE ZERO ORGANIZATION ?
TELL ME ABOUT WHERE WE GET  LINK WE HAVE TO SUBMIT ON PROJECTS FORM WHICH YOU WILL RELEASE ?
TELL ME CAN I CHANGE MY SUBMITTY PASSWORD BECAUSE ANYONE CAN LOGIN  BY MOBILE NO AND EMAIL ID CREDENTIALS?
SIR PROBLEM 3 HAS NO PROBLEM STATEMENT ?
SIR IT IS NECESSARY TO DO 0_PRACTICE_FACTORIAL_UNITTESTING PROBLEM ?
![Screenshot (19)](https://user-images.githubusercontent.com/101577287/161028403-f82d62d1-9b65-4785-8991-d91780cd4d1a.png)
I WILL BE THANKFUL IF YOU ANSWER MY QUERIES  please answer

**Comment by Bharathgopal** [comment]
You are violating the policy of keeping data confidential by posting images from our platforms.
Request you to use official communications to get clarity on these. 

This forum is only technical query related.
