### ISSUE TITLE
!URGENT! Assessment mail not received

### ISSUE THREAD

**Issue by vatsal26** [Bharathgopal/M1_March_2022#283]
I have received all the mails from company till now but the main which was send today regarding the assessment,I didn't receive it.
I have checked in my spam also

**Comment by Gnanesh45** [comment]
You will get the mail from Hackerearth platform.Keep refreshing Gmail

**Comment by Bharathgopal** [comment]
Request you to use official forum for this kind of communications. Keep the queries strictly toward technical in this forum.
