### ISSUE TITLE
issues while attending hacker earth

### ISSUE THREAD

**Issue by sakthiraambalasundaram** [Bharathgopal/M1_March_2022#288]
sir today i had attend hacker earth test in that while attending mcq it was fine but in coding section for me the keyboard not functioning if any key i pressed it exiting from full screen i had put query to hacker earth and team also. but they had said due to multiple switch it was logged out. it makes any problem to my program.

![issues](https://user-images.githubusercontent.com/65847751/161423342-cc8a569b-f42f-4a8e-a09b-f737b763816f.png)

**Comment by sakthiraambalasundaram** [comment]
![Screenshot_2022-04-03-21-39-58-44_e307a3f9df9f380ebaf106e1dc980bb6](https://user-images.githubusercontent.com/65847751/161437206-0df6ba05-6633-413d-b6e8-e41f23f8cac1.jpg)

**Comment by Bharathgopal** [comment]
Request you not to post any official communications here. This is purely technical forum. Any assessment related queries must be communicated through emails only.
