### ISSUE TITLE
Issue while uploading .c file in submitty

### ISSUE THREAD

**Issue by MNVS10** [Bharathgopal/M1_March_2022#289]
When I try to upload a file in submitty it shows "Child exited with status = 1" error.  The code  runs in my system compiler but shows error in Submitty. I tried more than 3 times but unable to solve the issue.

**Comment by Bharathgopal** [comment]
Submitty runs on Linux OS. If some code has bugs, it may or may not crash in windows but crashes in Linux.

**Solution:**
Check for execution of program on both Linux and Windows before submitting on Submitty.
