### ISSUE TITLE
not able to download linux certificate

### ISSUE THREAD

**Issue by mpulkit05** [Bharathgopal/M1_March_2022#5]
what to do?
where to get help?

**Comment by junaidferoz** [comment]
hey!! clock on cisco netacad and login and click on get certificate

**Comment by batcha333** [comment]
once after you complete your exam just close the current page and open your NDG unhatched linux link  again, u can able to download your certificate via a star icon!!!

**Comment by ITSMEUNICK-21** [comment]
Please have a look here : 
https://github.com/Bharathgopal/M1_March_2022/issues/23#issuecomment-1066687408

**Comment by Bharathgopal** [comment]
Duplicate of [Issue 23](https://github.com/Bharathgopal/M1_March_2022/issues/23)
